name: Changelog

on:
  pull_request:
  push:
    branches: [ master ]
    tags: [ "*" ]

permissions:
  contents: read

jobs:
  changelog:
    uses: owncloud/reusable-workflows/.github/workflows/calens.yml@ed7b4827feafc644f1fd1b723b7a1ca890480009 # main @ 2026-06-25
    secrets:
      APP_ID: ${{ secrets.CALENS_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.CALENS_APP_PRIVATE_KEY }}
